# Generated by Django 4.2.23 on 2025-06-23 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_category_color_size_supplier_taxcode_uom_warehouse_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(editable=False, max_length=10, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('personal_number', models.CharField(blank=True, max_length=15)),
                ('emergency_contact_number', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('aadhar_number', models.CharField(blank=True, max_length=14)),
                ('pan_number', models.CharField(blank=True, max_length=10)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('current_address', models.TextField(blank=True)),
                ('highest_qualification', models.CharField(blank=True, max_length=200)),
                ('previous_employer', models.CharField(blank=True, max_length=200)),
                ('total_experience_year', models.PositiveIntegerField(blank=True, null=True)),
                ('total_experience_month', models.PositiveIntegerField(blank=True, null=True)),
                ('relevant_experience_year', models.PositiveIntegerField(blank=True, null=True)),
                ('relevant_experience_month', models.PositiveIntegerField(blank=True, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('Married', 'Married'), ('Unmarried', 'Unmarried')], max_length=20)),
                ('basics', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('hra', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('conveyance_allowance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('medical_allowance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('other_allowances', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bonus', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('taxes', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pf', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('esi', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gross_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('net_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('uan_number', models.CharField(blank=True, max_length=12)),
                ('pf_number', models.CharField(blank=True, max_length=12)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('account_number', models.CharField(blank=True, max_length=20)),
                ('ifsc_code', models.CharField(blank=True, max_length=11)),
                ('asset', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=3)),
                ('asset_type', models.CharField(blank=True, max_length=50)),
                ('laptop_company_name', models.CharField(blank=True, max_length=50)),
                ('asset_id', models.CharField(blank=True, max_length=20)),
                ('upload_documents', models.TextField(blank=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.branch')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.department')),
                ('designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate_designations', to='core.role')),
            ],
        ),
    ]
