# Generated by Django 4.2.23 on 2025-07-11 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_id',
        ),
    ]
