# Generated by Django 5.2.4 on 2025-07-25 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_profile_profilepic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='name',
            new_name='department_name',
        ),
    ]
