# Generated by Django 5.2.4 on 2025-07-28 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_name_department_department_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='branch_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
