# Generated by Django 5.2.4 on 2025-07-29 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_department_branch_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.branch'),
        ),
        migrations.AddField(
            model_name='role',
            name='branch_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='role',
            name='department_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
