# Generated by Django 5.2.4 on 2025-07-29 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_role_branch_role_branch_name_role_department_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='name',
            new_name='role',
        ),
    ]
