# Generated by Django 5.2.4 on 2025-07-30 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_rename_name_role_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='upload_documents',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
