# Generated by Django 5.2.4 on 2025-07-30 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_candidate_upload_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='upload_documents',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
