# Generated by Django 5.2.4 on 2025-07-30 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_candidate_upload_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='upload_documents',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
