# Generated by Django 5.2.4 on 2025-07-30 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_candidate_upload_documents'),
    ]

    operations = [
    ]
