# Generated by Django 5.2.4 on 2025-07-30 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_convert_upload_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='upload_documents',
            field=models.TextField(blank=True, null=True),
        ),
    ]
