# Generated by Django 5.2.4 on 2025-07-30 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_candidate_upload_documents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='upload_documents',
        ),
    ]
