# Generated by Django 5.2.4 on 2025-07-30 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remove_candidate_upload_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='upload_documents',
            field=models.TextField(blank=True, null=True),
        ),
    ]
