# Generated by Django 5.2.4 on 2025-07-31 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_candidate_upload_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='reporting_to',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
