# Generated by Django 5.2.4 on 2025-07-31 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_profile_reporting_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='available_branches',
        ),
        migrations.AddField(
            model_name='profile',
            name='available_branches',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
