# Generated by Django 5.2.4 on 2025-08-07 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_profile_available_branches_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='custom_value',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_custom',
        ),
        migrations.AddField(
            model_name='product',
            name='product_id',
            field=models.CharField(blank=True, editable=False, max_length=10, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='RelatedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related_to', models.CharField(blank=True, max_length=255, null=True)),
                ('custom_value', models.CharField(blank=True, max_length=255, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_products_old', to='core.product')),
            ],
            options={
                'unique_together': {('product', 'related_to')},
            },
        ),
    ]
