# Generated by Django 5.2.4 on 2025-08-07 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_remove_product_custom_value_remove_product_is_custom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(default='CVB00N', editable=False, max_length=10, unique=True),
        ),
    ]
