# Generated by Django 5.2.4 on 2025-08-07 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_remove_product_product_id_product_custom_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='custom_value',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_custom',
        ),
        migrations.AddField(
            model_name='product',
            name='product_id',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
    ]
