# Generated by Django 5.2.4 on 2025-08-08 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_product_custom_category_product_custom_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='related_products',
        ),
        migrations.AddField(
            model_name='product',
            name='related_products',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
