# Generated by Django 5.2.4 on 2025-08-08 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_remove_product_related_products_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='custom_related_products',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_custom_category',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_custom_color',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_custom_related_products',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_custom_size',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_custom_supplier',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_custom_tax_code',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_custom_uom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_custom_warehouse',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='related_products',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
