# Generated by Django 5.2.4 on 2025-08-11 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='assigned_sales_rep',
            field=models.ForeignKey(limit_choices_to={'department': 6}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.candidate'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='available_limit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
