# Generated by Django 5.2.4 on 2025-08-13 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_purchaseorder_purchaseordercomment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='upload_file_path',
            field=models.FilePathField(blank=True, null=True, path='upload/'),
        ),
    ]
