# Generated by Django 5.2.4 on 2025-08-13 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_alter_purchaseorder_upload_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='upload_file_path',
            field=models.FileField(blank=True, null=True, upload_to='upload/'),
        ),
    ]
