# Generated by Django 5.2.4 on 2025-08-13 11:22

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_alter_purchaseorder_upload_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='PO_date',
            field=models.DateField(default=core.models.get_default_po_date),
        ),
        migrations.AlterField(
            model_name='purchaseordercomment',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
