# Generated by Django 5.2.4 on 2025-07-25 06:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enquiry_id', models.CharField(max_length=10, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('street_address', models.CharField(blank=True, max_length=200)),
                ('apartment', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postal', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('enquiry_type', models.CharField(choices=[('Product', 'Product'), ('Service', 'Service')], max_length=50)),
                ('enquiry_description', models.TextField(blank=True)),
                ('enquiry_channels', models.CharField(blank=True, choices=[('Phone', 'Phone'), ('Email', 'Email'), ('Web Form', 'Web Form'), ('Facebook', 'Facebook'), ('Twitter', 'Twitter'), ('Instagram', 'Instagram'), ('LinkedIn', 'LinkedIn')], max_length=50)),
                ('source', models.CharField(choices=[('WebSite', 'WebSite'), ('Referral', 'Referral'), ('Online Advertising', 'Online Advertising'), ('Offline Advertising', 'Offline Advertising'), ('Facebook', 'Facebook'), ('Twitter', 'Twitter'), ('Instagram', 'Instagram'), ('LinkedIn', 'LinkedIn')], max_length=50)),
                ('how_heard_this', models.CharField(blank=True, choices=[('WebSite', 'WebSite'), ('Referral', 'Referral'), ('Social Media', 'Social Media'), ('Event', 'Event'), ('Search Engine', 'Search Engine'), ('Other', 'Other')], max_length=50)),
                ('urgency_level', models.CharField(blank=True, choices=[('Immediately', 'Immediately'), ('Within 1-3 Months', 'Within 1-3 Months'), ('Within 6 Months', 'Within 6 Months'), ('Just Researching', 'Just Researching')], max_length=50)),
                ('enquiry_status', models.CharField(choices=[('New', 'New'), ('In Process', 'In Process'), ('Closed', 'Closed')], max_length=20)),
                ('priority', models.CharField(blank=True, choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EnquiryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=10)),
                ('product_description', models.CharField(max_length=200)),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('enquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='crm.enquiry')),
            ],
        ),
    ]
